# Generated by Django 2.2.3 on 2019-07-26 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('fatherName', models.CharField(max_length=200)),
                ('phoneNumber', models.BigIntegerField()),
                ('password', models.CharField(max_length=200)),
                ('nationalId', models.BigIntegerField()),
                ('birthday', models.DateField(default='2000-11-11')),
                ('male', models.BooleanField(default=False)),
                ('region', models.CharField(default='Iran', max_length=200)),
                ('number', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LoanInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.BigIntegerField()),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=10)),
                ('intrest', models.BigIntegerField()),
                ('maxInstallment', models.BigIntegerField()),
                ('minInstallment', models.BigIntegerField()),
                ('lowestAmount', models.BigIntegerField()),
                ('highestAmount', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loaninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loan.LoanInfo')),
            ],
            bases=('loan.loaninfo',),
        ),
    ]
