# Generated by Django 2.2.3 on 2019-07-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awesomeTwitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='background',
            field=models.CharField(default='../../static/awesomeTwitter/profile/mountain-1.jpg', max_length=400),
        ),
    ]
