# Generated by Django 2.2.3 on 2019-08-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awesomeTwitter', '0002_person_background'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('see_main_page', 'go_others_page'),)},
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default=12, max_length=200),
        ),
    ]
